[programs.devnet] 
<<<<<<< HEAD
zebec = "zbcKGdAmXfthXY3rEPBzexVByT2cqRqCZb9NwWdGQ2T" 
serum_multisig = "b6ZPysThkApNx2YDiGsPUiYPE7Ub1kTRdCWp7gBkzbr" 
[programs.localnet] 
zebec = "zbcKGdAmXfthXY3rEPBzexVByT2cqRqCZb9NwWdGQ2T" 
serum_multisig = "b6ZPysThkApNx2YDiGsPUiYPE7Ub1kTRdCWp7gBkzbr" 
[programs.mainnet] 
zebec = "zbcKGdAmXfthXY3rEPBzexVByT2cqRqCZb9NwWdGQ2T" 
=======
zebec = "DMFbM74dfiii1eHdutvjUFwuP8zdMrycGRfrMwKCtB5w" 
serum_multisig = "b6ZPysThkApNx2YDiGsPUiYPE7Ub1kTRdCWp7gBkzbr" 

[programs.localnet] 
zebec = "DMFbM74dfiii1eHdutvjUFwuP8zdMrycGRfrMwKCtB5w" 
>>>>>>> master
serum_multisig = "b6ZPysThkApNx2YDiGsPUiYPE7Ub1kTRdCWp7gBkzbr" 
  
[registry] 
url = "https://anchor.projectserum.com" 

[provider] 
cluster = "devnet" 
wallet = "~/.config/solana/id.json" 

  
[scripts] 
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/**" 