[programs.devnet]
zebec = "Gvg5iMmgu8zs4rn5zJ6YGGnzsu6WqZJawKUndbqneXia"
serum_multisig = "5BU6x2H7WXeyaP75D7daNJQAipZfVUr5FM9zdhzajK6p"
[programs.localnet]
serum_multisig = "7yAc31uU6YzsLVzeKMkFpQTTjiMwcCEZg2ojh14Rq6be"
zebec = "FfEvEBBnUFSLtetZmU7yA9wDECvTy1MryMy2QkVH3fQa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/**.ts"
