[programs.localnet]
zebec = "3svmYpJGih9yxkgqpExNdQZLKQ7Wu5SEjaVUbmbytUJg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/samundrakarki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
